services:
  snaptime-backend:
    container_name: snaptime_backend
    # image: ghcr.io/snaptime-app/backend
    build: .
    restart: always
    volumes:
      - uploads:/app/uploads:rw
    ports:
      - 8081:8080
    env_file:
      - .env.prod
  
volumes:
  uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/srv/snaptime'
